# Databricks notebook source
# MAGIC %sql
# MAGIC create schema if not exists silver.logistic;

# COMMAND ----------

# DBTITLE 1,Cell 2
# MAGIC %sql
# MAGIC ALTER TABLE silver.logistic.SALES_DATA_PRIOR_DAY
# MAGIC ADD COLUMN YARD_KEY INT AFTER YARD_ID;

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TABLE silver.logistic.SALES_DATA_PRIOR_DAY (
# MAGIC     YARD_ID STRING,
# MAGIC     YARD_KEY INT,
# MAGIC     YARD STRING,
# MAGIC     MATERIAL_NAME STRING,
# MAGIC     MATERIAL_CODE STRING,
# MAGIC     COMMODITY_NAME STRING,
# MAGIC     COMMODITY_TYPE STRING,
# MAGIC     OUTBOUND_TICKET_ID STRING,
# MAGIC     LATEST_SHIP_DATE STRING,
# MAGIC     LATEST_PAYMENT_DATE STRING,
# MAGIC     INVOICE_ISSUE_DATE STRING,
# MAGIC     INVOICE_STATUS STRING,
# MAGIC     INVOICE_NOTES STRING,
# MAGIC     CUSTOMER_NAME STRING,
# MAGIC     SALES_ORDER_ID STRING,
# MAGIC     OUTBOUND_TICKET_STATUS STRING,
# MAGIC     INVOICE_ID STRING,
# MAGIC     TAX_RATE STRING,
# MAGIC     CONSUMER_GROSS STRING,
# MAGIC     CONSUMER_TARE STRING,
# MAGIC     CONSUMER_NET_WEIGHT STRING,
# MAGIC     UM STRING,
# MAGIC     PRICE STRING,
# MAGIC     SELL_PRICE STRING,
# MAGIC     INVOICE_SUBTOTAL STRING,
# MAGIC     INVOICE_TOTAL STRING,
# MAGIC     INVOICE_FREIGHT_TOTAL STRING,
# MAGIC     AMOUNT_PAID STRING,
# MAGIC     PAYMENT_ADJUSTMENTS STRING,
# MAGIC     INVOICE_GRAND_TOTAL STRING,
# MAGIC     INVOICE_BALANCE_REMAINING STRING,
# MAGIC     COST_OF_GOODS_SOLD STRING,
# MAGIC     GROSS_MARGIN_DOLLAR STRING,
# MAGIC     MARGIN_PERCENTAGE STRING,
# MAGIC     NET_WEIGHT_SOLD STRING,
# MAGIC     WEIGHT_DIFFERENTIAL STRING,
# MAGIC     CURRENCY STRING,
# MAGIC     ACCOUNT_MANAGER STRING,
# MAGIC     CONVERTED_TOTAL STRING,
# MAGIC     IS_EXPORT STRING,
# MAGIC     MILL_SCALE_NUMBER STRING,
# MAGIC     ADDED_BY STRING,
# MAGIC     ADDED_ON timestamp,
# MAGIC     MODIFIED_BY STRING,
# MAGIC     MODIFIED_ON timestamp
# MAGIC );

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TABLE silver.logistic.APPOINTMENT_DATA (
# MAGIC     YARD_NAME STRING,
# MAGIC     APPOINTMENT_NUMBER STRING,
# MAGIC     APPOINTMENT_TITLE STRING,
# MAGIC     REFERENCE_TYPE STRING,
# MAGIC     SALES_ORDER_TICKET_ID STRING,
# MAGIC     PURCHASE_ORDER_TICKET_ID STRING,
# MAGIC     INBOUND_TICKET_ID STRING,
# MAGIC     OUTBOUND_TICKET_ID STRING,
# MAGIC     CUSTOMER_ID STRING,
# MAGIC     CARRIER_NAME STRING,
# MAGIC     DRIVER_NAME STRING,
# MAGIC     ORDER_FULFILLED STRING,
# MAGIC     APPOINTMENT_STATUS STRING,
# MAGIC     SCHEDULED_START STRING,
# MAGIC     SCHEDULED_END STRING,
# MAGIC     SHIPMENT_TYPE STRING,
# MAGIC     VESSEL STRING,
# MAGIC     SHIPPING_LINE_NAME STRING,
# MAGIC     FORWARDER_NVOCC STRING,
# MAGIC     ESTIMATED_TIME_OF_ARRIVAL STRING,
# MAGIC     ESTIMATED_TIME_OF_DEPARTURE STRING,
# MAGIC     EARLIEST_RETURN_DATE STRING,
# MAGIC     DOCUMENTATION_CUTOFF_DEADLINE STRING,
# MAGIC     CARGO_CUTOFF_DEADLINE STRING,
# MAGIC     EXPORT_REFERENCE_NUMBER STRING,
# MAGIC     CONTAINER_TYPE STRING,
# MAGIC     NUMBER_OF_CONTAINERS STRING,
# MAGIC     VOYAGE STRING,
# MAGIC     SCHEDULED_DURATION_HOURS STRING,
# MAGIC     APPOINTMENT_DATE STRING,
# MAGIC     DAY_OF_WEEK STRING,
# MAGIC     IS_FUTURE STRING,
# MAGIC     IS_ACTIVE STRING,
# MAGIC     CREATED_AT STRING,
# MAGIC     CREATED_BY STRING,
# MAGIC     CREATED_BY_EMAIL STRING,
# MAGIC     UPDATED_AT STRING,
# MAGIC     UPDATED_BY STRING,
# MAGIC     UPDATED_BY_EMAIL STRING,
# MAGIC     ADDED_BY STRING,
# MAGIC     ADDED_ON timestamp,
# MAGIC     MODIFIED_BY STRING,
# MAGIC     MODIFIED_ON timestamp
# MAGIC );

# COMMAND ----------

